name: notes-app

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
        - name: Code Clone from GitHub
          uses: actions/checkout@v1
          
        - name: Docker login
          env:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

        - name: Docker image build and push to docker repo
          run: |
            docker build -t dsdevops50/notes-app:latest .
            docker push dsdevops50/notes-app:latest
